---
# TITLE & AUTHOR
title: "StartupEngineer Example"
subtitle: "Create beautiful interactive slide decks with Reveal.js"
author: "Joschka Schwarz"
institute: "Hamburg University of Technology"
date: today
date-format: "dddd, D. MMMM YYYY"
# FORMAT OPTIONS
format: 
  startupengineer-revealjs:
    width: 1600
    height: 900
    footer: "Quarto StartupEngineer Theme"
---

```{r}
#| include: false
sysfonts::font_add_google("Poppins", "poppinslight", regular.wt=200, bold.wt=500)
# font_add_google("Poppins", "Poppins")
showtext::showtext_auto()
# To Do: Create TIE ggplot theme
source("_extensions/jwarz/startupengineer/setup-ggplot2-tie.R")
```

# In the morning {data-stack-name="In the morning"}

## Getting up

-   Turn off alarm
-   Get out of bed

## Breakfast

-   Eat eggs
-   Drink coffee

# In the evening {data-stack-name="In the evening"}

## Dinner

-   Eat spaghetti
-   Drink wine

## Going to sleep

-   Get in bed
-   Count sheep

# Code Blocks

## Example plot

TODO: Create TIE ggplot theme

```{r}
library(ggplot2)

diamonds |> 
  ggplot(aes(x=clarity, y=carat, color=price)) +
  geom_point(alpha=0.5, position="jitter")
```


# Hide Menubar

## Animated Lord Icons {data-state="hide-menubar"}

See https://lordicon.com/

{{< li lupuorrc trigger=loop speed=0.5 scale=50 colors="primary:#00C1D4,secondary:#005e73" >}}

{{< li nxaaasqe trigger=loop speed=0.5 scale=50 colors="primary:#00C1D4,secondary:#005e73" >}}

{{< li rjzlnunf trigger=loop speed=0.5 scale=50 colors="primary:#00C1D4,secondary:#005e73" >}}

{{< include _extensions/jwarz/startupengineer/about.qmd >}}
